### ISSUE TITLE
Run on linux server

### ISSUE THREAD

**Issue by pptrick** [facebookresearch/interaction-exploration#1]
Can this code run on a Linux server (without a screen)? If so, what extra configuration should I do?

**Comment by Tushar-N** [comment]
Unfortunately, the only way I got this to run was with an X server. You don't need a physical screen, but you do need to run something like `sudo Xorg -noreset +extension GLX +extension RENDER -logfile ./10.log -config ./xorg.conf :0` for each GPU.
