### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by zkytony** [facebookresearch/interaction-exploration#4]
How long does it take to train the different networks, including the three networks used in the proposed approach, and the baselines? What was the hardware used for training?

Thanks!

**Comment by Tushar-N** [comment]
For intexp agents: ~8 hours on 1 Quadro RTX 6000 GPU (16 parallel environments)
For segmentation network (offline): ~30 mins

All training tensorboard logs can be downloaded using the script [here](https://github.com/facebookresearch/interaction-exploration/blob/master/interaction_exploration/tools/download_data.sh).

**Comment by zkytony** [comment]
That's impressive! How much memory does the network for intexp and segmentation network take? (Can it be trained on a GPU with like 8GB or 10GB memory?)

**Comment by Tushar-N** [comment]
I think it's about 12GB memory. I was training these on K40m's at some point, which had 12GB memory. If you use the distributed version of the habitat codebase (modified for THOR), you can fit a lot more processes (8-16 on each GPU) without running out of memory.

**Comment by zkytony** [comment]
Just to make sure, are you referring to the use of `LambdaLR` in `ppo_trainer.py` included in your repo?

**Comment by Tushar-N** [comment]
No, the ppo code I used for these experiments is _not_ distributed, but it is possible to fork the habitat-lab codebase and re-purpose it for THOR to use DDPPO out of the box. This codebase does not support that right now, sorry.
