### ISSUE TITLE
Memory requirement

### ISSUE THREAD

**Issue by zkytony** [facebookresearch/interaction-exploration#5]
I am able to run the evaluation command in the README:
```
export UNETCKPT=`ls interaction_exploration/cv/intexp/run0/unet/*.ckpt`
python -m interaction_exploration.run \
    --config interaction_exploration/config/intexp.yaml \
    --mode eval \
    ENV.NUM_STEPS 1024 \
    NUM_PROCESSES 32 \
    EVAL.DATASET interaction_exploration/data/test_episodes_K_16.json \
    TORCH_GPU_ID 0 X_DISPLAY :0 \
    CHECKPOINT_FOLDER interaction_exploration/cv/intexp/run0/ \
    LOAD interaction_exploration/cv/intexp/run0/ckpt.24.pth \
    MODEL.BEACON_MODEL $UNETCKPT
```
But my computer (16GB RAM) ran out of memory. What's the minimum required memory to run this command?

**Comment by Tushar-N** [comment]
I haven't profiled the eval script, but I submitted jobs with about 64GB memory in the past. Worst case, you can always reduce the number of parallel environments (from 32 to 8, or even 1) but this comes at a cost of much slower evaluation.
