### ISSUE TITLE
Change AI2-THOR scene in kb_agent.py

### ISSUE THREAD

**Issue by rex131** [facebookresearch/interaction-exploration#8]
hi, I am trying to run kn_agent.py, but i want to change the AI2-THOR scene. i have some trouble because it is alwasys default scene like 
![image](https://user-images.githubusercontent.com/87143368/146233210-a33bcd03-21a5-4860-85de-95ead37ba2ee.png)
what should i do?
sorry for your time. looking forward to your replay!

**Comment by Tushar-N** [comment]
`cfg.DEBUG` is set for the kb_agent which defaults to using FloorPlan1. You can change it [here](https://github.com/facebookresearch/interaction-exploration/blob/e4310f5a82f6432233eba6584c88949dc799d097/envs/thor.py#L156).
